### ISSUE TITLE
Error occurred during isocirc pipeline run 

### ISSUE THREAD

**Issue by aman21392** [Xinglab/isoCirc#1]
== 11:48:56-Jan-11-2021 == [itst_intergenic] bedtools intersect -v -a output_chr1_control/isocirc.bed.exon.gtf -b /Drive4/nanopore_2nd_experiment/isocirc_nanopore/output_chr1_control/Homo_sapiens.GRCh38.96.gtf.gene.bed > output_chr1_control/isocirc.bed.intergenic.out
== 11:48:56-Jan-11-2021 == [itst_exon] bedtools intersect -a output_chr1_control/isocirc.bed.exon.gtf -b /Drive4/nanopore_2nd_experiment/isocirc_nanopore/output_chr1_control/Homo_sapiens.GRCh38.96.gtf.exon.gtf -wa -wb > output_chr1_control/isocirc.bed.exon.out
== 11:48:59-Jan-11-2021 == [output_isoform_eval] Writing isoform-wise evaluation result to file ...
== 11:48:59-Jan-11-2021 == [output_isoform_eval] Writing isoform-wise evaluation result to file done!
[E::idx_find_and_load] Could not retrieve index file for 'output_chr1_control/high.bam'
Traceback (most recent call last):
  File "/home/aclab/.local/bin/isocirc", line 219, in <module>
    main()
  File "/home/aclab/.local/bin/isocirc", line 216, in main
    isocirc_core(args)
  File "/home/aclab/.local/bin/isocirc", line 135, in isocirc_core
    isoform_out, bed_out, stats_out)
  File "/home/aclab/.local/lib/python3.6/site-packages/isocirc/hcBSJ_fullIso.py", line 829, in hcBSJ_fullIso
    bs.stats_core(long_len, cons_info, high_bam, isoform_out_fn, all_bsj_stats_dict, stats_out_fn)
  File "/home/aclab/.local/lib/python3.6/site-packages/isocirc/basic_stats.py", line 123, in stats_core
    tot_map_read_n, tot_map_cons_n, tot_map_cons_base, error_rate = get_error_rate(cons_bam)
  File "/home/aclab/.local/lib/python3.6/site-packages/isocirc/basic_stats.py", line 37, in get_error_rate
    return tot_mapped_read_n, tot_mapped_cons_n, tot_mapped_base, '{0:.1f}%'.format((tot_ins+tot_del+tot_mis) / (tot_ins+tot_mis+tot_match+0.0) * 100)
ZeroDivisionError: float division by zero

Can you please tell me how to sort out this issue. Thanks in advance.

**Comment by aman21392** [comment]
Command which I used-- 
/home/aclab/apps/isoCirc/isoCirc_pipeline/isocirc/isocirc -t 70 control_T.fa /Drive4/nanopore_2nd_experiment/human_genome/Homo_sapiens.GRCh38.dna.chromosome.1.fa /Drive4/nanopore_2nd_experiment/Homo_sapiens.GRCh38.96.gtf circbase_hg38.bed output_chr1_control

**Comment by yangao07** [comment]
The error message

> ZeroDivisionError: float division by zero

indicates that one record in the SAM alignment file has a length of 0. 
This is very weird. I will fix this issue.
Yan

**Comment by yangao07** [comment]
Try the latest version (v1.0.1), should be fixed now.

**Comment by aman21392** [comment]
Thanks, it fixed now. I have questions like if I used a different protocol for library preparation as it is given in some papers like "Profiling of circular RNA N6‐methyladenosine in Moso bamboo (Phyllostachys edulis) using nanopore‐based direct RNA sequencing" and also in "Nanopore sequencing of full-length circRNAs in human and mouse brains reveals circRNA-specific exon usage and intron retention". These 2 papers fragment the circRNA and then sequenced it. So is it also ok for this pipeline. I used this pipeline but didn't get any circRNA. I used chromosome 1 and the output file is vacant.
So please can you suggest to me what can i do. Thanks in advance

**Comment by yangao07** [comment]
isoCirc pipeline is designed for isoCirc data, which is RCA-based long-read data.
So it can not be used on regular circRNA data.
