### ISSUE TITLE
Error on test data

### ISSUE THREAD

**Issue by TasfiaZahin** [Xinglab/isoCirc#11]
Hello,

I have been trying to run isocirc on the given test data (command: isocirc -t 1 read_toy.fa chr16_toy.fa chr16_toy.gtf chr16_circRNA_toy.bed output) but am running into the following error. I saw a similar problem in one of the previous git issues related to biopython version. My biopython version shows Version: 1.81 (which should work I believe). Can you please help me out with this? Thanks in advance!

== 12:04:25-Nov-16-2023 == [check_dependencies] Checking dependencies ...

== 12:04:25-Nov-16-2023 == [check_dependencies] Checking dependencies done!

== 12:04:25-Nov-16-2023 == [Tandem-Repeats-Finder] Finding tandem repeats with TRF ...

== 12:04:25-Nov-16-2023 == [Tandem Repeats Finder] trf409.legacylinux64 read_toy.fa 2 7 7 80 10 100 2000 -h -ngs > output/trf.out

== 12:04:27-Nov-16-2023 == [Tandem-Repeats-Finder] Finding tandem repeats with TRF done!

== 12:04:27-Nov-16-2023 == [Mapping] Mapping consensus sequence to genome ...

== 12:04:27-Nov-16-2023 == [Mapping] minimap2 -ax splice -ub --MD --eqx chr16_toy.fa output/cons.fa -t 1 > output/cons.fa.sam

[M::mm_idx_gen::0.013*1.11] collected minimizers

[M::mm_idx_gen::0.031*1.05] sorted minimizers

[M::main::0.031*1.05] loaded/built the index for 1 target sequence(s)

[M::mm_mapopt_update::0.033*1.04] mid_occ = 34

[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1

[M::mm_idx_stat::0.035*1.04] distinct minimizers: 43525 (97.01% are singletons); average occurrences: 1.104; average spacing: 4.161; total length: 200000

[M::worker_pipeline::0.308*1.00] mapped 44 sequences

[M::main] Version: 2.20-r1061

[M::main] CMD: minimap2 -ax splice -ub --MD --eqx -t 1 chr16_toy.fa output/cons.fa

[M::main] Real time: 0.315 sec; CPU: 0.316 sec; Peak RSS: 0.035 GB

== 12:04:27-Nov-16-2023 == [Mapping] Mapping consensus sequence to genome done!

== 12:04:27-Nov-16-2023 == [Classifying] Classifying consensus alignment ...

== 12:04:27-Nov-16-2023 == [classify_bam_core] Processing output/cons.fa.sam ...

== 12:04:27-Nov-16-2023 == [classify_bam_core] Processing output/cons.fa.sam done.

== 12:04:27-Nov-16-2023 == [Classifying] Classifying consensus alignment done!

== 12:04:27-Nov-16-2023 == [gtfToGenePred] gtfToGenePred -ignoreGroupsWithoutExons chr16_toy.gtf /datadisk1/tkz5115/circRNA_long_reads/tools/isoCirc/test_data/output/chr16_toy.gtf.gene_pred

== 12:04:27-Nov-16-2023 == [genePredToBed] genePredToBed /datadisk1/tkz5115/circRNA_long_reads/tools/isoCirc/test_data/output/chr16_toy.gtf.gene_pred /datadisk1/tkz5115/circRNA_long_reads/tools/isoCirc/test_data/output/chr16_toy.gtf.bed

== 12:04:27-Nov-16-2023 == [get_transcript_from_gtf] Loading transcript from chr16_toy.gtf ...

== 12:04:27-Nov-16-2023 == [get_transcript_from_gtf] Loading transcript from chr16_toy.gtf done!

== 12:04:27-Nov-16-2023 == [get_splice_site_from_bed12] Loading splice site from /datadisk1/tkz5115/circRNA_long_reads/tools/isoCirc/test_data/output/chr16_toy.gtf.bed ...

== 12:04:27-Nov-16-2023 == [get_splice_site_from_bed12] Loading splice site from /datadisk1/tkz5115/circRNA_long_reads/tools/isoCirc/test_data/output/chr16_toy.gtf.bed done!

== 12:04:27-Nov-16-2023 == [get_splice_junction_from_bed12] Loading splice junction from /datadisk1/tkz5115/circRNA_long_reads/tools/isoCirc/test_data/output/chr16_toy.gtf.bed ...

== 12:04:27-Nov-16-2023 == [get_splice_junction_from_bed12] Loading splice junction from /datadisk1/tkz5115/circRNA_long_reads/tools/isoCirc/test_data/output/chr16_toy.gtf.bed done!

== 12:04:27-Nov-16-2023 == [get_exon_from_bed12] Loading exon from /datadisk1/tkz5115/circRNA_long_reads/tools/isoCirc/test_data/output/chr16_toy.gtf.bed ...

== 12:04:27-Nov-16-2023 == [get_exon_from_bed12] Loading exon from /datadisk1/tkz5115/circRNA_long_reads/tools/isoCirc/test_data/output/chr16_toy.gtf.bed done!

== 12:04:27-Nov-16-2023 == [get_back_splice_junction_from_bed] Loading splice junction from chr16_circRNA_toy.bed ...

== 12:04:27-Nov-16-2023 == [get_back_splice_junction_from_bed] Loading splice junction from chr16_circRNA_toy.bed done!

== 12:04:27-Nov-16-2023 == [read_wise_eval] Generating read-wise evaluation result ...

== 12:04:27-Nov-16-2023 == [get_cigar_from_pairwise_res] Unexpected alignment string: target GAGCTGCAAG-T----CACCTCCTG 0.

**Comment by yangao07** [comment]
Looks like isocirc used the old version of biopython that caused this error.
Can you show me the output of `pip install isocirc`?

**Comment by TasfiaZahin** [comment]
Here is it.

Requirement already satisfied: isocirc in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (1.0.6a0)

Requirement already satisfied: biopython in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from isocirc) (1.81)

Requirement already satisfied: gffutils in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from isocirc) (0.12)

Requirement already satisfied: pyinterval in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from isocirc) (1.2.0)

Requirement already satisfied: mappy in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from isocirc) (2.26)

Requirement already satisfied: matplotlib in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from isocirc) (3.5.3)

Requirement already satisfied: numpy in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from isocirc) (1.21.6)

Requirement already satisfied: pandas in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from isocirc) (1.3.5)

Requirement already satisfied: pyfaidx in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from isocirc) (0.7.2.2)

Requirement already satisfied: pysam in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from isocirc) (0.22.0)

Requirement already satisfied: six>=1.12.0 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from gffutils->isocirc) (1.16.0)

Requirement already satisfied: argh>=0.26.2 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from gffutils->isocirc) (0.27.2)

Requirement already satisfied: argcomplete>=1.9.4 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from gffutils->isocirc) (3.1.2)

Requirement already satisfied: simplejson in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from gffutils->isocirc) (3.19.2)

Requirement already satisfied: setuptools in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from pyfaidx->isocirc) (40.8.0)

Requirement already satisfied: importlib-metadata in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from pyfaidx->isocirc) (6.7.0)

Requirement already satisfied: cycler>=0.10 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from matplotlib->isocirc) (0.11.0)

Requirement already satisfied: fonttools>=4.22.0 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from matplotlib->isocirc) (4.38.0)

Requirement already satisfied: kiwisolver>=1.0.1 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from matplotlib->isocirc) (1.4.5)

Requirement already satisfied: packaging>=20.0 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from matplotlib->isocirc) (23.2)

Requirement already satisfied: pillow>=6.2.0 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from matplotlib->isocirc) (9.5.0)

Requirement already satisfied: pyparsing>=2.2.1 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from matplotlib->isocirc) (3.1.1)

Requirement already satisfied: python-dateutil>=2.7 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from matplotlib->isocirc) (2.8.2)

Requirement already satisfied: pytz>=2017.3 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from pandas->isocirc) (2023.3.post1)

Requirement already satisfied: crlibm==1.*,>=1.0.3 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from pyinterval->isocirc) (1.0.3)

Requirement already satisfied: zipp>=0.5 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from importlib-metadata->pyfaidx->isocirc) (3.15.0)

Requirement already satisfied: typing-extensions>=3.6.4 in /datadisk1/tkz5115/circRNA_long_reads/tools/.venv/lib/python3.7/site-packages (from importlib-metadata->pyfaidx->isocirc) (4.7.1)

WARNING: There was an error checking the latest version of pip.

**Comment by yangao07** [comment]
This is caused by the update of biopython>=1.80. 
Actually, isocirc v1.0.6 was updated based on the change in biopython-1.79, and they now changed it back in >=1.80.
Right now the latest isocirc is compatible with biopython >=1.80.

**Comment by TasfiaZahin** [comment]
Hello,

I have tried running version 1.0.7 and it works fine on the test data but I am still getting the same error when I run it on human tissue data (fasta). I have used ensembl GRCh37 reference and annotation, and circbase bed file for the input parameters. Here is a part of the error. It will be very helpful if you can give some isights on this, thanks in advance!

== 06:31:02-Nov-25-2023 == [classify_bam_core] 4300000 BAM records done ...

== 06:31:05-Nov-25-2023 == [classify_bam_core] 4400000 BAM records done ...

== 06:31:09-Nov-25-2023 == [classify_bam_core] 4500000 BAM records done ...

== 06:31:12-Nov-25-2023 == [classify_bam_core] 4600000 BAM records done ...

== 06:31:16-Nov-25-2023 == [classify_bam_core] 4700000 BAM records done ...

== 06:31:19-Nov-25-2023 == [classify_bam_core] 4800000 BAM records done ...

== 06:31:22-Nov-25-2023 == [classify_bam_core] 4900000 BAM records done ...

== 06:31:26-Nov-25-2023 == [classify_bam_core] 5000000 BAM records done ...

== 06:31:29-Nov-25-2023 == [classify_bam_core] 5100000 BAM records done ...

== 06:31:33-Nov-25-2023 == [classify_bam_core] 5200000 BAM records done ...

== 06:31:36-Nov-25-2023 == [classify_bam_core] 5300000 BAM records done ...

== 06:31:40-Nov-25-2023 == [classify_bam_core] 5400000 BAM records done ...

== 06:31:43-Nov-25-2023 == [classify_bam_core] 5500000 BAM records done ...

== 06:31:47-Nov-25-2023 == [classify_bam_core] 5600000 BAM records done ...

== 06:31:50-Nov-25-2023 == [classify_bam_core] 5700000 BAM records done ...

== 06:31:53-Nov-25-2023 == [classify_bam_core] 5800000 BAM records done ...

== 06:31:57-Nov-25-2023 == [classify_bam_core] 5900000 BAM records done ...

== 06:32:00-Nov-25-2023 == [classify_bam_core] 6000000 BAM records done ...

== 06:32:04-Nov-25-2023 == [classify_bam_core] 6100000 BAM records done ...

== 06:32:07-Nov-25-2023 == [classify_bam_core] 6200000 BAM records done ...

== 06:32:11-Nov-25-2023 == [classify_bam_core] 6300000 BAM records done ...

== 06:32:14-Nov-25-2023 == [classify_bam_core] 6400000 BAM records done ...

== 06:32:17-Nov-25-2023 == [classify_bam_core] 6500000 BAM records done ...

== 06:32:21-Nov-25-2023 == [classify_bam_core] 6600000 BAM records done ...

== 06:32:24-Nov-25-2023 == [classify_bam_core] 6700000 BAM records done ...

== 06:32:28-Nov-25-2023 == [classify_bam_core] 6800000 BAM records done ...

== 06:32:29-Nov-25-2023 == [classify_bam_core] Processing /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/cons.fa.sam done.

== 06:32:29-Nov-25-2023 == [Classifying] Classifying consensus alignment done!

== 06:34:40-Nov-25-2023 == [gtfToGenePred] gtfToGenePred -ignoreGroupsWithoutExons /datadisk1/tkz5115/human_GRCh37_ensembl/Homo_sapiens.GRCh37.87.gtf /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/Homo_sapiens.GRCh37.87.gtf.gene_pred

== 06:34:57-Nov-25-2023 == [genePredToBed] genePredToBed /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/Homo_sapiens.GRCh37.87.gtf.gene_pred /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/Homo_sapiens.GRCh37.87.gtf.bed

== 06:34:58-Nov-25-2023 == [get_transcript_from_gtf] Loading transcript from /datadisk1/tkz5115/human_GRCh37_ensembl/Homo_sapiens.GRCh37.87.gtf ...

== 06:35:06-Nov-25-2023 == [get_transcript_from_gtf] Loading transcript from /datadisk1/tkz5115/human_GRCh37_ensembl/Homo_sapiens.GRCh37.87.gtf done!

== 06:35:06-Nov-25-2023 == [get_splice_site_from_bed12] Loading splice site from /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/Homo_sapiens.GRCh37.87.gtf.bed ...

== 06:35:08-Nov-25-2023 == [get_splice_site_from_bed12] Loading splice site from /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/Homo_sapiens.GRCh37.87.gtf.bed done!

== 06:35:08-Nov-25-2023 == [get_splice_junction_from_bed12] Loading splice junction from /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/Homo_sapiens.GRCh37.87.gtf.bed ...

== 06:35:09-Nov-25-2023 == [get_splice_junction_from_bed12] Loading splice junction from /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/Homo_sapiens.GRCh37.87.gtf.bed done!

== 06:35:09-Nov-25-2023 == [get_exon_from_bed12] Loading exon from /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/Homo_sapiens.GRCh37.87.gtf.bed ...

== 06:35:11-Nov-25-2023 == [get_exon_from_bed12] Loading exon from /datadisk1/tkz5115/circRNA_long_reads/prostate/isocirc_out/Homo_sapiens.GRCh37.87.gtf.bed done!

== 06:35:11-Nov-25-2023 == [get_back_splice_junction_from_bed] Loading splice junction from /datadisk1/tkz5115/circRNA_long_reads/circbase/hsa_hg19_circRNA.bed ...

== 06:35:11-Nov-25-2023 == [get_back_splice_junction_from_bed] Loading splice junction from /datadisk1/tkz5115/circRNA_long_reads/circbase/hsa_hg19_circRNA.bed done!

== 06:35:38-Nov-25-2023 == [read_wise_eval] Generating read-wise evaluation result ...

== 06:36:05-Nov-25-2023 == [get_cigar_from_pairwise_res] Unexpected alignment string: ATTGCTGGAT-------------------------------------------TG----- 12 query.

**Comment by yangao07** [comment]
This looks like the same error you met on the test data, which should be fixed.
You can try to install the latest one from the source, I made some changes regarding this.

git clone https://github.com/Xinglab/isoCirc.git
cd isoCirc/isoCirc_pipeline && pip install .

**Comment by TasfiaZahin** [comment]
It worked now. Thanks a lot!
