### ISSUE TITLE
circRNA annotation

### ISSUE THREAD

**Issue by KateK** [Xinglab/isoCirc#2]
Is there a possibility to run without bed with known circRNAs?

Regards,
Kasia

**Comment by yangao07** [comment]
The bed file is a positional input option for isocirc.
If you do not have known circRNAs to provide, you can simply use the one in the `test_data` folder.
This will not cause any difference for the BSJ or full-length circRNA identification.

**Comment by KateK** [comment]
Thank You for the quick reply! :)
