### ISSUE TITLE
[E::idx_find_and_load] Could not retrieve index file

### ISSUE THREAD

**Issue by Qiongyi** [Xinglab/isoCirc#4]
Hi Yan and Yi,

I was using isoCirc to run the toy example in "test_data". It could go through the pipeline and generate all the output files. However, I noticed that there are several warnings messages complaining that some program could not retrieve index files for high.bam and low.bam (shown below).

[M::mm_idx_gen::0.033*0.27] collected minimizers
[M::mm_idx_gen::0.040*0.39] sorted minimizers
[M::main::0.040*0.39] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.040*0.40] mid_occ = 34
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.041*0.41] distinct minimizers: 43525 (97.01% are singletons); average occurrences: 1.104; average spacing: 4.161; total length: 200000
[M::worker_pipeline::0.229*0.89] mapped 44 sequences
[M::main] Version: 2.17-r974-dirty
[M::main] CMD: minimap2 -ax splice -ub --MD --eqx -t 1 chr16_toy.fa output/cons.fa
[M::main] Real time: 0.231 sec; CPU: 0.207 sec; Peak RSS: 0.033 GB
[E::idx_find_and_load] Could not retrieve index file for 'output/high.bam'
[E::idx_find_and_load] Could not retrieve index file for 'output/high.bam'
[E::idx_find_and_load] Could not retrieve index file for 'output/high.bam'
[E::idx_find_and_load] Could not retrieve index file for 'output/high.bam'
[E::idx_find_and_load] Could not retrieve index file for 'output/high.bam'
[E::idx_find_and_load] Could not retrieve index file for 'output/low.bam'
[E::idx_find_and_load] Could not retrieve index file for 'output/high.bam'
== 12:58:37-May-24-2021 == [check_dependencies] Checking dependencies ...
== 12:58:37-May-24-2021 == [check_dependencies] Checking dependencies done!
== 12:58:37-May-24-2021 == [Tandem-Repeats-Finder] Finding tandem repeats with TRF ...

I tried to run my own datasets and got the same warning messages. I was wondering where did these warning messages come from? Does it affect the output files?

Thanks,

Qiongyi

**Comment by Qiongyi** [comment]
BTW. I was using the latest version of isoCirc (v1.0.2).

**Comment by yangao07** [comment]
You could just ignore those warnings, nothing bad will happen.
