### ISSUE TITLE
Issues of not generating correct file by using isoCirc

### ISSUE THREAD

**Issue by Mortis-hub** [Xinglab/isoCirc#8]
I’m using the isoCirc from your lab, it worked on your test data. But when I download your data from ebi (https://www.ebi.ac.uk/ena/browser/view/PRJNA594380?show=reads) and using isoCirc by the following command (I downloaded the data and put it straight into the pipeline without other steps):

ref=/home/fengyige/data/star/hg19/hg19.fa

gtf=/home/fengyige/data/star/hg19/gencode.v21.annotation.gtf

circ=/home/fengyige/data/circRNA/hsa_hg19_circRNA.bed

input=/home/fengyige/20220826_circrna/fastq/SRR10612056_1.fastq.gz

isocirc -t 20 ${input} ${ref} ${gtf} ${circ} ../SRR10612056/

It did generate isocirc.bed and isocirc.out, but it didn't generate isocirc_stats.out. And the *out file only contains the header line. I wonder if the data downloaded from ebi need some pre-processing? Or I just miss some critical steps？

Thanks for your help!

**Comment by yangao07** [comment]
Can you paste all the output information when running isocirc?

**Comment by Mortis-hub** [comment]
I ran it twice, this is the log message for the first time, the second time ended accidentally:

[M::mm_idx_gen::84.469*1.92] collected minimizers
[M::mm_idx_gen::97.170*2.66] sorted minimizers
[M::main::97.170*2.66] loaded/built the index for 24 target sequence(s)
[M::mm_mapopt_update::101.671*2.58] mid_occ = 654
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 24
[M::mm_idx_stat::103.601*2.55] distinct minimizers: 166959269 (35.52% are singletons); average occurrences: 5.868; average spacing: 3.160; total length: 3095677412
[M::worker_pipeline::1586.385*7.65] mapped 1218705 sequences
[M::worker_pipeline::3042.487*7.82] mapped 1215707 sequences
[M::worker_pipeline::4495.867*7.88] mapped 1213095 sequences
[M::worker_pipeline::5802.347*7.88] mapped 1099061 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -ax splice -ub --MD --eqx -t 8 /home/fengyige/data/star/hg19/hg19.fa ./SRR10612050//cons.fa
[M::main] Real time: 5802.786 sec; CPU: 45743.837 sec; Peak RSS: 22.140 GB
== 17:02:13-Sep-12-2022 == [check_dependencies] Checking dependencies ...
== 17:02:13-Sep-12-2022 == [check_dependencies] Checking dependencies done!
== 17:02:13-Sep-12-2022 == [Tandem-Repeats-Finder] Finding tandem repeats with TRF ...
== 17:02:13-Sep-12-2022 == [fxtools] fxtools qa ../fastq/SRR10612050_1.fastq.gz > ./SRR10612050//long_reads.fa 2> /dev/null
== 17:07:36-Sep-12-2022 == [fxtools] fxtools sx ./SRR10612050//long_reads.fa 8 /home/fengyige/20220826_circrna/iso_out/SRR10612050/
== 17:08:10-Sep-12-2022 == [Tandem Repeats Finder] trf409.legacylinux64 /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.1 2 7 7 80 10 100 2000 -h -ngs > ./SRR10612050//trf.out.1; rm /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.1
== 17:08:10-Sep-12-2022 == [Tandem Repeats Finder] trf409.legacylinux64 /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.2 2 7 7 80 10 100 2000 -h -ngs > ./SRR10612050//trf.out.2; rm /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.2
== 17:08:10-Sep-12-2022 == [Tandem Repeats Finder] trf409.legacylinux64 /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.3 2 7 7 80 10 100 2000 -h -ngs > ./SRR10612050//trf.out.3; rm /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.3
== 17:08:10-Sep-12-2022 == [Tandem Repeats Finder] trf409.legacylinux64 /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.4 2 7 7 80 10 100 2000 -h -ngs > ./SRR10612050//trf.out.4; rm /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.4
== 17:08:10-Sep-12-2022 == [Tandem Repeats Finder] trf409.legacylinux64 /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.5 2 7 7 80 10 100 2000 -h -ngs > ./SRR10612050//trf.out.5; rm /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.5
== 17:08:10-Sep-12-2022 == [Tandem Repeats Finder] trf409.legacylinux64 /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.6 2 7 7 80 10 100 2000 -h -ngs > ./SRR10612050//trf.out.6; rm /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.6
== 17:08:10-Sep-12-2022 == [Tandem Repeats Finder] trf409.legacylinux64 /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.7 2 7 7 80 10 100 2000 -h -ngs > ./SRR10612050//trf.out.7; rm /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.7
== 17:08:10-Sep-12-2022 == [Tandem Repeats Finder] trf409.legacylinux64 /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.8 2 7 7 80 10 100 2000 -h -ngs > ./SRR10612050//trf.out.8; rm /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.8
== 10:53:51-Sep-13-2022 == [Tandem Repeats Finder] cat ./SRR10612050//trf.out.1 >> ./SRR10612050//trf.out; rm ./SRR10612050//trf.out.1
== 10:54:08-Sep-13-2022 == [Tandem Repeats Finder] cat ./SRR10612050//trf.out.2 >> ./SRR10612050//trf.out; rm ./SRR10612050//trf.out.2
== 10:54:29-Sep-13-2022 == [Tandem Repeats Finder] cat ./SRR10612050//trf.out.3 >> ./SRR10612050//trf.out; rm ./SRR10612050//trf.out.3
== 10:54:51-Sep-13-2022 == [Tandem Repeats Finder] cat ./SRR10612050//trf.out.4 >> ./SRR10612050//trf.out; rm ./SRR10612050//trf.out.4
== 10:55:10-Sep-13-2022 == [Tandem Repeats Finder] cat ./SRR10612050//trf.out.5 >> ./SRR10612050//trf.out; rm ./SRR10612050//trf.out.5
== 10:55:28-Sep-13-2022 == [Tandem Repeats Finder] cat ./SRR10612050//trf.out.6 >> ./SRR10612050//trf.out; rm ./SRR10612050//trf.out.6
== 10:55:52-Sep-13-2022 == [Tandem Repeats Finder] cat ./SRR10612050//trf.out.7 >> ./SRR10612050//trf.out; rm ./SRR10612050//trf.out.7
== 10:56:14-Sep-13-2022 == [Tandem Repeats Finder] cat ./SRR10612050//trf.out.8 >> ./SRR10612050//trf.out; rm ./SRR10612050//trf.out.8
== 10:56:35-Sep-13-2022 == [fxtools] fxtools lp ./SRR10612050//long_reads.fa > /home/fengyige/20220826_circrna/iso_out/SRR10612050/long_reads.fa.len 2> /dev/null
== 11:27:17-Sep-13-2022 == [Tandem-Repeats-Finder] Finding tandem repeats with TRF done!
== 11:27:17-Sep-13-2022 == [Mapping] Mapping consensus sequence to genome ...
== 11:27:17-Sep-13-2022 == [Mapping] minimap2 -ax splice -ub --MD --eqx /home/fengyige/data/star/hg19/hg19.fa ./SRR10612050//cons.fa -t 8 > ./SRR10612050//cons.fa.sam
== 13:04:01-Sep-13-2022 == [Mapping] Mapping consensus sequence to genome done!
== 13:04:01-Sep-13-2022 == [Classifying] Classifying consensus alignment ...
== 13:04:01-Sep-13-2022 == [classify_bam_core] Processing ./SRR10612050//cons.fa.sam ... 
== 13:04:06-Sep-13-2022 == [classify_bam_core] 100000 BAM records done ... 
== 13:04:10-Sep-13-2022 == [classify_bam_core] 200000 BAM records done ... 
== 13:04:14-Sep-13-2022 == [classify_bam_core] 300000 BAM records done ... 
== 13:04:19-Sep-13-2022 == [classify_bam_core] 400000 BAM records done ... 
== 13:04:23-Sep-13-2022 == [classify_bam_core] 500000 BAM records done ... 
== 13:04:27-Sep-13-2022 == [classify_bam_core] 600000 BAM records done ... 
== 13:04:31-Sep-13-2022 == [classify_bam_core] 700000 BAM records done ... 
== 13:04:35-Sep-13-2022 == [classify_bam_core] 800000 BAM records done ... 
== 13:04:39-Sep-13-2022 == [classify_bam_core] 900000 BAM records done ... 
== 13:04:44-Sep-13-2022 == [classify_bam_core] 1000000 BAM records done ... 
== 13:04:48-Sep-13-2022 == [classify_bam_core] 1100000 BAM records done ... 
== 13:04:53-Sep-13-2022 == [classify_bam_core] 1200000 BAM records done ... 
== 13:04:57-Sep-13-2022 == [classify_bam_core] 1300000 BAM records done ... 
== 13:05:01-Sep-13-2022 == [classify_bam_core] 1400000 BAM records done ... 
== 13:05:05-Sep-13-2022 == [classify_bam_core] 1500000 BAM records done ... 
== 13:05:10-Sep-13-2022 == [classify_bam_core] 1600000 BAM records done ... 
== 13:05:14-Sep-13-2022 == [classify_bam_core] 1700000 BAM records done ... 
== 13:05:18-Sep-13-2022 == [classify_bam_core] 1800000 BAM records done ... 
== 13:05:23-Sep-13-2022 == [classify_bam_core] 1900000 BAM records done ... 
== 13:05:27-Sep-13-2022 == [classify_bam_core] 2000000 BAM records done ... 
== 13:05:31-Sep-13-2022 == [classify_bam_core] 2100000 BAM records done ... 
== 13:05:36-Sep-13-2022 == [classify_bam_core] 2200000 BAM records done ... 
== 13:05:40-Sep-13-2022 == [classify_bam_core] 2300000 BAM records done ... 
== 13:05:44-Sep-13-2022 == [classify_bam_core] 2400000 BAM records done ... 
== 13:05:48-Sep-13-2022 == [classify_bam_core] 2500000 BAM records done ... 
== 13:05:53-Sep-13-2022 == [classify_bam_core] 2600000 BAM records done ... 
== 13:05:57-Sep-13-2022 == [classify_bam_core] 2700000 BAM records done ... 
== 13:06:01-Sep-13-2022 == [classify_bam_core] 2800000 BAM records done ... 
== 13:06:06-Sep-13-2022 == [classify_bam_core] 2900000 BAM records done ... 
== 13:06:10-Sep-13-2022 == [classify_bam_core] 3000000 BAM records done ... 
== 13:06:14-Sep-13-2022 == [classify_bam_core] 3100000 BAM records done ... 
== 13:06:19-Sep-13-2022 == [classify_bam_core] 3200000 BAM records done ... 
== 13:06:23-Sep-13-2022 == [classify_bam_core] 3300000 BAM records done ... 
== 13:06:27-Sep-13-2022 == [classify_bam_core] 3400000 BAM records done ... 
== 13:06:31-Sep-13-2022 == [classify_bam_core] 3500000 BAM records done ... 
== 13:06:35-Sep-13-2022 == [classify_bam_core] 3600000 BAM records done ... 
== 13:06:40-Sep-13-2022 == [classify_bam_core] 3700000 BAM records done ... 
== 13:06:44-Sep-13-2022 == [classify_bam_core] 3800000 BAM records done ... 
== 13:06:48-Sep-13-2022 == [classify_bam_core] 3900000 BAM records done ... 
== 13:06:52-Sep-13-2022 == [classify_bam_core] 4000000 BAM records done ... 
== 13:06:56-Sep-13-2022 == [classify_bam_core] 4100000 BAM records done ... 
== 13:07:01-Sep-13-2022 == [classify_bam_core] 4200000 BAM records done ... 
== 13:07:05-Sep-13-2022 == [classify_bam_core] 4300000 BAM records done ... 
== 13:07:09-Sep-13-2022 == [classify_bam_core] 4400000 BAM records done ... 
== 13:07:13-Sep-13-2022 == [classify_bam_core] 4500000 BAM records done ... 
== 13:07:17-Sep-13-2022 == [classify_bam_core] 4600000 BAM records done ... 
== 13:07:21-Sep-13-2022 == [classify_bam_core] 4700000 BAM records done ... 
== 13:07:26-Sep-13-2022 == [classify_bam_core] 4800000 BAM records done ... 
== 13:07:30-Sep-13-2022 == [classify_bam_core] 4900000 BAM records done ... 
[E::idx_find_and_load] Could not retrieve index file for './SRR10612050//high.bam'
[E::idx_find_and_load] Could not retrieve index file for './SRR10612050//high.bam'
[E::idx_find_and_load] Could not retrieve index file for './SRR10612050//high.bam'
[E::idx_find_and_load] Could not retrieve index file for './SRR10612050//high.bam'
[E::idx_find_and_load] Could not retrieve index file for './SRR10612050//high.bam'
[E::idx_find_and_load] Could not retrieve index file for './SRR10612050//low.bam'
== 13:07:34-Sep-13-2022 == [classify_bam_core] 5000000 BAM records done ... 
== 13:07:38-Sep-13-2022 == [classify_bam_core] 5100000 BAM records done ... 
== 13:07:42-Sep-13-2022 == [classify_bam_core] 5200000 BAM records done ... 
== 13:07:46-Sep-13-2022 == [classify_bam_core] 5300000 BAM records done ... 
== 13:07:51-Sep-13-2022 == [classify_bam_core] 5400000 BAM records done ... 
== 13:07:55-Sep-13-2022 == [classify_bam_core] 5500000 BAM records done ... 
== 13:07:59-Sep-13-2022 == [classify_bam_core] 5600000 BAM records done ... 
== 13:08:03-Sep-13-2022 == [classify_bam_core] 5700000 BAM records done ... 
== 13:08:07-Sep-13-2022 == [classify_bam_core] 5800000 BAM records done ... 
== 13:08:12-Sep-13-2022 == [classify_bam_core] 5900000 BAM records done ... 
== 13:08:16-Sep-13-2022 == [classify_bam_core] 6000000 BAM records done ... 
== 13:08:20-Sep-13-2022 == [classify_bam_core] 6100000 BAM records done ... 
== 13:08:24-Sep-13-2022 == [classify_bam_core] 6200000 BAM records done ... 
== 13:08:28-Sep-13-2022 == [classify_bam_core] 6300000 BAM records done ... 
== 13:08:33-Sep-13-2022 == [classify_bam_core] 6400000 BAM records done ... 
== 13:08:37-Sep-13-2022 == [classify_bam_core] 6500000 BAM records done ... 
== 13:08:42-Sep-13-2022 == [classify_bam_core] 6600000 BAM records done ... 
== 13:08:46-Sep-13-2022 == [classify_bam_core] 6700000 BAM records done ... 
== 13:08:50-Sep-13-2022 == [classify_bam_core] 6800000 BAM records done ... 
== 13:08:54-Sep-13-2022 == [classify_bam_core] 6900000 BAM records done ... 
== 13:08:59-Sep-13-2022 == [classify_bam_core] 7000000 BAM records done ... 
== 13:09:03-Sep-13-2022 == [classify_bam_core] 7100000 BAM records done ... 
== 13:09:07-Sep-13-2022 == [classify_bam_core] Processing ./SRR10612050//cons.fa.sam done.
== 13:09:07-Sep-13-2022 == [Classifying] Classifying consensus alignment done!
== 13:10:40-Sep-13-2022 == [gtfToGenePred] gtfToGenePred -genePredExt -ignoreGroupsWithoutExons /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.gene_pred
== 13:10:46-Sep-13-2022 == [genePredToBed] genePredToBed /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.gene_pred /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.bed
== 13:10:47-Sep-13-2022 == [get_transcript_from_bed12] Loading transcript from /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.gene_pred ... 
== 13:10:49-Sep-13-2022 == [get_transcript_from_gene_pred] Loading transcript from /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.gene_pred done!
== 13:10:49-Sep-13-2022 == [get_splice_site_from_bed12] Loading splice site from /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.bed ... 
== 13:10:51-Sep-13-2022 == [get_splice_site_from_bed12] Loading splice site from /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.bed done!
== 13:10:51-Sep-13-2022 == [get_splice_junction_from_bed12] Loading splice junction from /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.bed ... 
== 13:10:53-Sep-13-2022 == [get_splice_junction_from_bed12] Loading splice junction from /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.bed done!
== 13:10:53-Sep-13-2022 == [get_exon_from_bed12] Loading exon from /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.bed ... 
== 13:10:55-Sep-13-2022 == [get_exon_from_bed12] Loading exon from /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.bed done!
== 13:10:55-Sep-13-2022 == [get_back_splice_junction_from_bed] Loading splice junction from /home/fengyige/data/circRNA/hsa_hg19_circRNA.bed ... 
== 13:10:55-Sep-13-2022 == [get_back_splice_junction_from_bed] Loading splice junction from /home/fengyige/data/circRNA/hsa_hg19_circRNA.bed done!
== 13:11:04-Sep-13-2022 == [read_wise_eval] Generating read-wise evaluation result ... 
== 13:14:02-Sep-13-2022 == [high_quality] 100000 high mapping quality BAM records have been processed ... 
== 13:17:10-Sep-13-2022 == [high_quality] 200000 high mapping quality BAM records have been processed ... 
== 13:20:19-Sep-13-2022 == [high_quality] 300000 high mapping quality BAM records have been processed ... 
== 13:23:28-Sep-13-2022 == [high_quality] 400000 high mapping quality BAM records have been processed ... 
== 13:26:32-Sep-13-2022 == [high_quality] 500000 high mapping quality BAM records have been processed ... 
== 13:29:35-Sep-13-2022 == [high_quality] 600000 high mapping quality BAM records have been processed ... 
== 13:32:34-Sep-13-2022 == [high_quality] 700000 high mapping quality BAM records have been processed ... 
== 13:35:33-Sep-13-2022 == [high_quality] 800000 high mapping quality BAM records have been processed ... 
== 13:38:32-Sep-13-2022 == [high_quality] 900000 high mapping quality BAM records have been processed ... 
== 13:41:32-Sep-13-2022 == [high_quality] 1000000 high mapping quality BAM records have been processed ... 
== 13:44:33-Sep-13-2022 == [high_quality] 1100000 high mapping quality BAM records have been processed ... 
== 13:47:32-Sep-13-2022 == [high_quality] 1200000 high mapping quality BAM records have been processed ... 
== 13:50:34-Sep-13-2022 == [high_quality] 1300000 high mapping quality BAM records have been processed ... 
== 13:53:34-Sep-13-2022 == [high_quality] 1400000 high mapping quality BAM records have been processed ... 
== 13:56:34-Sep-13-2022 == [high_quality] 1500000 high mapping quality BAM records have been processed ... 
== 13:59:35-Sep-13-2022 == [high_quality] 1600000 high mapping quality BAM records have been processed ... 
== 14:02:35-Sep-13-2022 == [high_quality] 1700000 high mapping quality BAM records have been processed ... 
== 14:05:36-Sep-13-2022 == [high_quality] 1800000 high mapping quality BAM records have been processed ... 
== 14:06:16-Sep-13-2022 == [read_wise_eval] Generating read-wise evaluation result done!
== 14:06:16-Sep-13-2022 == [filter_circRNA_read] Filtering back-splice-junctions ...
== 14:07:06-Sep-13-2022 == [filter_circRNA_read] Filtering back-splice-junctions done!
== 14:07:06-Sep-13-2022 == [rescue_reads] Rescuing reads using reliable back-splice-junctions ...
== 14:07:33-Sep-13-2022 == [rescue_reads] Rescuing reads using reliable back-splice-junctions done!
== 14:07:33-Sep-13-2022 == [uniq_isoform_with_unsorted_coors] Generating isoform-wise evaluation result ... 
== 14:07:33-Sep-13-2022 == [uniq_isoform_with_unsorted_coors] Generating isoform-wise evaluation result done!
== 14:07:34-Sep-13-2022 == [bed2exonGtf] bed2exonGtf ./SRR10612050//isocirc.bed ./SRR10612050//isocirc.bed.exon.gtf
== 14:07:35-Sep-13-2022 == [exonGtf] awk -v OFS="\t" '($3=="exon"){print}' /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf > /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.exon.gtf
== 14:07:38-Sep-13-2022 == [gtf2bed] awk -v OFS="\t" '($3=="gene"){print $1,$4-1,$5}' /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf > /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.gene.bed
== 14:07:39-Sep-13-2022 == [gtf2bed] awk -v OFS="\t" '($3=="CDS"){print}' /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf > /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.cds.gtf
== 14:07:42-Sep-13-2022 == [gtf2bed] awk -v OFS="\t" '($3=="UTR" || $3=="five_prime_utr" || $3=="three_prime_utr"){print}' /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf > /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.utr.gtf
== 14:07:44-Sep-13-2022 == [gtf2bed] awk -v OFS="\t" '($3=="exon" && ($0 ~ /gene_biotype "lincRNA"/ || $0 ~ /gene_type "lincRNA"/)){print}' /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf > /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.lincRNA.gtf
== 14:07:46-Sep-13-2022 == [gtf2bed] awk -v OFS="\t" '($3=="exon" && ($0 ~ /gene_biotype "antisense"/ || $0 ~ /gene_type "antisense"/)){print}' /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf > /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.antisense.gtf
== 14:07:47-Sep-13-2022 == [gtf2bed] awk -v OFS="\t" '($3=="exon" && ($0 ~ /gene_biotype "rRNA"/ || $0 ~ /gene_type "rRNA"/)){print}' /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf > /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.rRNA.gtf
== 14:08:00-Sep-13-2022 == [bed2exonGtf] bed2exonGtf ./SRR10612050//isocirc.bed.five.site.bed ./SRR10612050//isocirc.bed.five.site.exon.gtf
== 14:08:01-Sep-13-2022 == [bed2exonGtf] bed2exonGtf ./SRR10612050//isocirc.bed.three.site.bed ./SRR10612050//isocirc.bed.three.site.exon.gtf
== 14:08:03-Sep-13-2022 == [bed2exonGtf] bed2exonGtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.five.site.bed /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.five.site.exon.gtf
== 14:08:06-Sep-13-2022 == [bed2exonGtf] bed2exonGtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.three.site.bed /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.three.site.exon.gtf
== 14:08:09-Sep-13-2022 == [itst_gtf_gtf] itst_gtf_gtf ./SRR10612050//isocirc.bed.five.site.exon.gtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.five.site.exon.gtf ./SRR10612050//isocirc.bed.five.site.gene.out
== 14:08:10-Sep-13-2022 == [itst_gtf_gtf] itst_gtf_gtf ./SRR10612050//isocirc.bed.three.site.exon.gtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.three.site.exon.gtf ./SRR10612050//isocirc.bed.three.site.gene.out
== 14:08:11-Sep-13-2022 == [gtf2gene] gtf2gene ./SRR10612050//isocirc.bed.exon.gtf /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf ./SRR10612050//isocirc.bed.ovlp.gene.out
== 14:08:14-Sep-13-2022 == [itst_gtf_bed] itst_gtf_bed ./SRR10612050//isocirc.bed.exon.gtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.cds.gtf ./SRR10612050//isocirc.bed.CDS.out
== 14:08:15-Sep-13-2022 == [itst_gtf_bed] itst_gtf_bed ./SRR10612050//isocirc.bed.exon.gtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.utr.gtf ./SRR10612050//isocirc.bed.UTR.out
== 14:08:16-Sep-13-2022 == [itst_gtf_bed] itst_gtf_bed ./SRR10612050//isocirc.bed.exon.gtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.lincRNA.gtf ./SRR10612050//isocirc.bed.lincRNA.out
== 14:08:17-Sep-13-2022 == [itst_gtf_bed] itst_gtf_bed ./SRR10612050//isocirc.bed.exon.gtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.antisense.gtf ./SRR10612050//isocirc.bed.antisense.out
== 14:08:18-Sep-13-2022 == [itst_gtf_bed] itst_gtf_bed ./SRR10612050//isocirc.bed.exon.gtf /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.rRNA.gtf ./SRR10612050//isocirc.bed.rRNA.out
== 14:08:19-Sep-13-2022 == [itst_intron] bedtools intersect -v -a ./SRR10612050//isocirc.bed.exon.gtf -b /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.bed -split > ./SRR10612050//isocirc.bed.intron.out
== 14:08:22-Sep-13-2022 == [itst_intergenic] bedtools intersect -v -a ./SRR10612050//isocirc.bed.exon.gtf -b /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.gene.bed > ./SRR10612050//isocirc.bed.intergenic.out
== 14:08:29-Sep-13-2022 == [itst_exon] bedtools intersect -a ./SRR10612050//isocirc.bed.exon.gtf -b /home/fengyige/20220826_circrna/iso_out/SRR10612050/gencode.v21.annotation.gtf.exon.gtf -wa -wb > ./SRR10612050//isocirc.bed.exon.out
== 14:08:31-Sep-13-2022 == [get_block_anno] No "exon_number" found in record.

**Comment by yangao07** [comment]
Seems like the `exon_number` tag is missing from the GTF file you specify.
Can you try the command `grep exon_number /home/fengyige/data/star/hg19/gencode.v21.annotation.gtf | head`?

**Comment by Mortis-hub** [comment]
Turns out that my GTF file from UCSC has lost some message. I'm now using the GTF file from ensembl and it finally work successfully. Thanks for your help!

**Comment by yangao07** [comment]
Great!
